name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: RajeevSivarasasingam/podcast-generator@main
        with:
          skip-services: "true"
          python-packages-from: "pip"
